name: 'Cache > Save'
description: 'Save a cache artifact'
author: 'Martijn Hols (forked from the GitHub cache action)'
inputs:
  path:
    description: 'A list of files, directories, and wildcard patterns to save'
    required: true
  key:
    description: 'An explicit key for saving the cache'
    required: true
  upload-chunk-size:
    description: 'The chunk size used to split up large files during upload, in bytes'
    required: false
runs:
  using: 'node12'
  main: '../dist/saveOnly/index.js'
branding:
  icon: 'archive'
  color: 'gray-dark'
